import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import api from "../api/axios";

export default function ArchiveVault() {
  const navigate = useNavigate();
  const [archives, setArchives] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchVault = async () => {
      try {
        const res = await api.get("/books/admin/archive/books", {
          headers: { Authorization: `Bearer ${localStorage.getItem('adminToken')}` }
        });
        setArchives(res.data.data);
      } catch (err) {
        setError("Failed to access the Archive Vault.");
      } finally {
        setLoading(false);
      }
    };
    fetchVault();
  }, []);

  const handleRestore = async (archiveId: number) => {
    try {
        await api.post(`/books/admin/restore/${archiveId}`, {}, {
            headers: { Authorization: `Bearer ${localStorage.getItem('adminToken')}` }
        });
        alert("Book restored successfully!");
        window.location.reload(); // Refresh to show it's gone from the vault
    } catch (err) {
        alert("Failed to restore book.");
    }
};

  const handleLogout = () => {
    localStorage.removeItem("adminToken"); localStorage.removeItem("role"); navigate("/librarian-login");
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh', fontFamily: 'sans-serif', backgroundColor: '#f8fafc' }}>
      
      {/* Sidebar */}
      <div style={{ width: '250px', backgroundColor: '#0f172a', color: 'white', padding: '20px' }}>
        <h3>Staff Panel</h3>
        <nav style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '30px' }}>
          <Link to="/admin/dashboard" style={{ color: 'white', textDecoration: 'none' }}>📊 Stats Overview</Link>
          <Link to="/add-book" style={{ color: 'white', textDecoration: 'none' }}>📚 Add New Book</Link>
          <Link to="/admin/books" style={{ color: 'white', textDecoration: 'none' }}>📖 Manage Books</Link>
          <Link to="/admin/vault" style={{ color: '#38bdf8', textDecoration: 'none' }}>🗄️ Archive Vault</Link>
          <button onClick={handleLogout} style={{ marginTop: '50px', backgroundColor: '#ef4444', color: 'white', border: 'none', padding: '10px', borderRadius: '4px', cursor: 'pointer' }}>Logout</button>
        </nav>
      </div>

      {/* Main Content */}
      <div style={{ flex: 1, padding: '40px' }}>
        <h2>🗄️ The Archive Vault</h2>
        <p style={{ color: '#64748b', marginTop: '-10px', marginBottom: '30px' }}>Soft-deleted records pending permanent 30-day purge.</p>

        {error && <div style={{ color: '#b91c1c', marginBottom: '15px', padding: '15px', backgroundColor: '#fef2f2', border: '1px solid #fca5a5', borderRadius: '4px', fontWeight: 'bold' }}>{error}</div>}

        <div style={{ backgroundColor: 'white', borderRadius: '8px', border: '1px solid #e2e8f0', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '14px', textAlign: 'left' }}>
            <thead>
              <tr style={{ backgroundColor: '#f1f5f9', color: '#475569' }}>
                <th style={{ padding: '15px 20px' }}>Original ID</th>
                <th style={{ padding: '15px 20px' }}>Archived Data (JSON Payload)</th>
                <th style={{ padding: '15px 20px' }}>Archived On</th>
                <th style={{ padding: '15px 20px', color: '#dc2626' }}>Purge Date</th>
              </tr>
            </thead>
            <tbody>
              {loading ? <tr><td colSpan={4} style={{ padding: '20px', textAlign: 'center' }}>Decrypting vault contents...</td></tr> : 
                archives.length === 0 ? <tr><td colSpan={4} style={{ padding: '20px', textAlign: 'center', color: '#64748b' }}>The vault is currently empty.</td></tr> :
                archives.map(arc => {
                  // Safely parse the JSON payload generated by our MySQL trigger
                  const payload = typeof arc.record_payload === 'string' ? JSON.parse(arc.record_payload) : arc.record_payload;
                  
                  return (
                    <tr key={arc.archive_id} style={{ borderBottom: '1px solid #e2e8f0' }}>
                    <td style={{ padding: '15px 20px', color: '#64748b', fontWeight: 'bold' }}>#{arc.original_id}</td>
                    <td style={{ padding: '15px 20px' }}>
                        <strong>{payload.title}</strong><br/>
                        <span style={{ fontSize: '12px', color: '#64748b', fontFamily: 'monospace' }}>ISBN: {payload.isbn}</span>
                    </td>
                    <td style={{ padding: '15px 20px' }}>{arc.archived_date}</td>
                    <td style={{ padding: '15px 20px', color: '#dc2626', fontWeight: 'bold' }}>{arc.deletion_date}</td>
                    
                    {/* ADD THIS CELL */}
                    <td style={{ padding: '15px 20px', textAlign: 'center' }}>
                        <button 
                        onClick={() => handleRestore(arc.archive_id)} 
                        style={{ padding: '6px 12px', backgroundColor: '#10b981', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}
                        >
                        Restore
                        </button>
                    </td>
                    </tr>
                  );
                })
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}